# Python Project
## T-bank flights and hotels dataset

## Step 1: Annotation

No more than 2 paragraphs outlining the main purpose and idea of the work and the distribution of contribution of each member of the team.

## Step 2: Dataset description

What subject area is your data from? How many and what kind of fields are in the dataset? What can you say about the data quality: are there any missing values, inconsistent values, wrong data types, etc.?

## Step 3: Description of the dataset

In [10]:
import pandas as pd

with open("dano_dataset_travel.csv",encoding="utf-8") as file:
    print(file.readline())

df = pd.read_csv("dano_dataset_travel.csv", sep=";",decimal=",",engine='pyarrow')
# Instant conversion of numeric data to float and conversion of dates to datetime64

order_online_payment_flg;account_rk;client_rk;order_rk;loyalty_program_type_nm;bundle_nm;order_type_cd;order_status_cd;party_first_order_dt;party_first_order_type_dt;free_cancel_booking_dttm;created_dttm;cancel_dttm;book_start_dttm;local_book_start_dttm;book_end_dttm;hotel_country;hotel_city;avia_dep_city;avia_arr_city;promo_code_discount_amt;loyalty_accrual_rub_amt;nominal_price_eur_amt;nominal_price_rub_amt;order_item_cnt;month_beginning_balance_rub;monthly_income_amt;suppress_email_flg;suppress_call_flg;bounce_cd;last_sms_success_flg;call_contact_6m_flg;call_contact_3m_flg;call_contact_1m_flg;good_email_address_flg;bad_email_address_flg;email_valid_flg;children_cnt;age;age_type_cd;parent_meeting_region_nm;delivery_region_category_cd;lvn_city_nm;lvn_state_nm;time_zone_delta_tm;time_zone_cd;last_used_product_cd;first_used_product_cd;mobile_phone_operator_nm;marital_status_cd;education_level_cd;birth_place;gender_cd;last_sms_dt;last_email_send_dt;last_session_dttm

### General overview

In [ ]:
print(f"The original size: {df.shape[0]:,} rows, {df.shape[1]} cols")
 
print("\nColumn dtypes and non-null counts:")
df.info()
 
print("\nOrder type distribution (order_type_cd):")
print(df['order_type_cd'].value_counts(dropna=False))
 
print("\nOrder status distribution (order_status_cd):")
print(df['order_status_cd'].value_counts(dropna=False))

Shape: 835,938 rows, 56 columns

Column dtypes and non-null counts:
<class 'pandas.DataFrame'>
RangeIndex: 835938 entries, 0 to 835937
Data columns (total 56 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   order_online_payment_flg     786885 non-null  float64
 1   account_rk                   835938 non-null  str
 2   client_rk                    835938 non-null  str
 3   order_rk                     835938 non-null  str
 4   loyalty_program_type_nm      754957 non-null  str
 5   bundle_nm                    588049 non-null  str
 6   order_type_cd                786885 non-null  str
 7   order_status_cd              779514 non-null  str
 8   party_first_order_dt         786885 non-null  object
 9   party_first_order_type_dt    786767 non-null  object
 10  free_cancel_booking_dttm     75600 non-null   datetime64[ns]
 11  created_dttm                 786885 non-null  datetime64[ns]
 12  cancel_dttm                  0 non-null       float64
 13  book_start_dttm              786885 non-null  datetime64[ns]
 14  local_book_start_dttm        786885 non-null  datetime64[ns]
 15  book_end_dttm                171548 non-null  datetime64[ns]
 16  hotel_country                162248 non-null  str
 17  hotel_city                   162248 non-null  str
 18  avia_dep_city                615275 non-null  str
 19  avia_arr_city                615275 non-null  str
 20  promo_code_discount_amt      615900 non-null  float64
 21  loyalty_accrual_rub_amt      475353 non-null  float64
 22  nominal_price_eur_amt        786885 non-null  float64
 23  nominal_price_rub_amt        786885 non-null  float64
 24  order_item_cnt               615337 non-null  float64
 25  month_beginning_balance_rub  776628 non-null  float64
 26  monthly_income_amt           673078 non-null  float64
 27  suppress_email_flg           835938 non-null  int64
 28  suppress_call_flg            835938 non-null  int64
 29  bounce_cd                    39675 non-null   float64
 30  last_sms_success_flg         833939 non-null  float64
 31  call_contact_6m_flg          271 non-null     float64
 32  call_contact_3m_flg          271 non-null     float64
 33  call_contact_1m_flg          271 non-null     float64
 34  good_email_address_flg       19798 non-null   float64
 35  bad_email_address_flg        19798 non-null   float64
 36  email_valid_flg              835938 non-null  int64
 37  children_cnt                 719699 non-null  float64
 38  age                          835937 non-null  float64
 39  age_type_cd                  835690 non-null  str
 40  parent_meeting_region_nm     786457 non-null  str
 41  delivery_region_category_cd  835938 non-null  str
 42  lvn_city_nm                  475969 non-null  str
 43  lvn_state_nm                 783169 non-null  str
 44  time_zone_delta_tm           835938 non-null  str
 45  time_zone_cd                 835938 non-null  str
 46  last_used_product_cd         835935 non-null  str
 47  first_used_product_cd        833478 non-null  str
 48  mobile_phone_operator_nm     834698 non-null  str
 49  marital_status_cd            520888 non-null  str
 50  education_level_cd           475104 non-null  str
 51  birth_place                  832973 non-null  str
 52  gender_cd                    825781 non-null  str
 53  last_sms_dt                  833939 non-null  object
 54  last_email_send_dt           19798 non-null   object
 55  last_session_dttm            835938 non-null  datetime64[ns]
dtypes: datetime64[ns](6), float64(18), int64(3), object(4), str(25)
memory usage: 666.4+ MB

Order type distribution (order_type_cd):
order_type_cd
AIR    615337
HOT    171548
NaN     49053
Name: count, dtype: int64

Order status distribution (order_status_cd):
order_status_cd
SUC    759950
NaN     56424
PRC     18467
ERR       650
NSH       304
CNC        84
REJ        58
BRN         1
Name: count, dtype: int64

### Descriptive statistics

In [5]:
numeric_cols = [
    'nominal_price_rub_amt',
    'monthly_income_amt',
    'age',
    'loyalty_accrual_rub_amt',
    'month_beginning_balance_rub'
]

for col in numeric_cols:
    df[col] = pd.to_numeric(
        df[col].astype(str).str.replace(',', '.', regex=False),
        errors='coerce'
    )


stats = df[numeric_cols].describe()
stats = stats.rename(index={'50%': '50% (median)'})
stats

,nominal_price_rub_amt,monthly_income_amt,age,loyalty_accrual_rub_amt,month_beginning_balance_rub
count,7.868850e+05,6.730780e+05,835937.000000,475353.000000,7.766280e+05
mean,1.517810e+04,1.473086e+05,36.073155,644.108014,4.259195e+04
std,2.402879e+04,2.660834e+05,9.370449,1586.753948,1.990449e+05
min,1.000000e+00,0.000000e+00,14.000000,-8645.000000,-1.498962e+07
25%,5.090000e+03,5.360000e+04,29.000000,154.000000,4.240000e+02
50% (median),9.342000e+03,9.715000e+04,35.000000,326.000000,5.282000e+03
75%,1.652700e+04,1.675000e+05,41.000000,682.000000,2.735925e+04
max,2.025808e+06,6.700000e+07,98.000000,606732.000000,2.370640e+07

In [7]:
df.describe(include="str")

,order_online_payment_flg,account_rk,client_rk,order_rk,loyalty_program_type_nm,bundle_nm,order_type_cd,order_status_cd,party_first_order_dt,party_first_order_type_dt,...,last_used_product_cd,first_used_product_cd,mobile_phone_operator_nm,marital_status_cd,education_level_cd,birth_place,gender_cd,last_sms_dt,last_email_send_dt,last_session_dttm
count,786885,835938,835938,835938,754957,588049,786885,779514,786885,786767,...,835935,833478,834698,520888,475104,832973,825781,833939,19798,835938
unique,1,133885,148364,786886,36,9,2,7,2500,2497,...,4,9,60,6,5,51954,2,428,256,86892
top,"1,0",9b2d5b4678781e53038e91ea5324530a03f27dc1d0e5f6...,a46735f4d392f42bd73943c6330a2c69028e33c166a73e...,9b2d5b4678781e53038e91ea5324530a03f27dc1d0e5f6...,Tinkoff Black,Premium,AIR,SUC,2019-03-08,2024-03-06,...,MPL,MPL,МТС,MAR,GRD,ГОР. МОСКВА,M,2024-07-03,2012-04-19,2024-11-06 17:36:31.000000
freq,786885,65421,359,49053,289081,292078,615337,759950,1241,1618,...,740428,589589,257099,228350,317249,18992,519702,64519,3789,379

## Step 4: Clean-up of the dataset

### Removing irrelevant columns

1. Identifier columns: just hashes, have no analytical value

In [4]:
id_cols = ['account_rk', 'client_rk', 'order_rk']

2. Almost empty columns (>90% rows are empty)

In [5]:
mostly_empty_cols = [
    'cancel_dttm',              # 100% empty
    'call_contact_6m_flg',      # 100 empty
    'call_contact_3m_flg',      # 100% empty
    'call_contact_1m_flg',      # 100% empty
    'bounce_cd',                # 95% empty
    'free_cancel_booking_dttm', # 91% empty
    'good_email_address_flg',   # 98% empty
    'bad_email_address_flg',    # 98% empty
    'last_email_send_dt',       # 98% empty
]

3. Other Columns

In [6]:
duplicate_cols = ['local_book_start_dttm'] # the same as the "book_start_dttm" column, but in the local time zone.
# No sense to keep them both

noisy_cols = ['birth_place'] # Place of birth: the text is too loose (city, region, country — all mixed up),
# difficult to use in analysis

In [7]:
cols_to_drop = id_cols + mostly_empty_cols + duplicate_cols + noisy_cols
df.drop(columns=cols_to_drop, inplace=True)

In [ ]:
print(f"After deleting: {df.shape[1]} columns left")

After deleting: 42 columns left

4. Correcting numeric columns

In [11]:
numeric_str_cols = [
    'promo_code_discount_amt',
    'loyalty_accrual_rub_amt',
    'nominal_price_eur_amt',
    'nominal_price_rub_amt',
    'order_item_cnt',
    'month_beginning_balance_rub',
    'monthly_income_amt',
    'children_cnt',
    'age',
]
 
for col in numeric_str_cols:
    df[col] = (
        df[col]
        .astype(str)
        .str.replace(',', '.', regex=False)
        .pipe(pd.to_numeric, errors='coerce')
    )
 
print("Numeric columns converted to float.")

Numeric columns converted to float.

5. Dates conversion

In [12]:
date_cols = [
    'party_first_order_dt',
    'party_first_order_type_dt',
    'created_dttm',
    'book_start_dttm',
    'book_end_dttm',
    'last_sms_dt',
    'last_session_dttm',
]
 
for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors='coerce')
 
print("Date columns converted into datetime.")

Date columns converted into datetime.

### Cleaning rows

1. Removing rows without orders

In [4]:
# More than 49000 rows have no information in the field order_type_cd, 
before = len(df)
df = df[df['order_type_cd'].notna()].copy()
print(f"The number of rows without an order deleted: {before - len(df):,}")

The number of rows without an order deleted: 49,053

2. Removing rows with incomplete orders

In [5]:
before = len(df)
df = df[df['order_status_cd'] == 'SUC'].copy()
print(f"Incomplete orders deleted: {before - len(df):,}")
print(f"Rows remain: {len(df):,}")

Incomplete orders deleted: 26,935
Rows remain: 759,950

3. Deleting rows with omissions in key fields

In [16]:
key_cols = ['nominal_price_rub_amt', 'age']
before = len(df)
df.dropna(subset=key_cols, inplace=True)
print(f"Deleted lines with omissions in key fields: {before - len(df):,}")

Deleted lines with omissions in key fields: 0

### Saving cleaned dataset

In [13]:
df.to_csv('travel_clean.csv', index=False)

## Step 5: Overview